Repository nove-org/NAPI, pull requests merged in 2023-08, with the labels that each got.

#84 Added pull request templates and changed the default message on code format
  .github/PULL_REQUEST_TEMPLATE/default.md
  .github/workflows/format.yml
Labels: chore

#86 Pull request templates
  PULL_REQUEST_TEMPLATE.md
Labels: fixes, chore

#89 Resolve various problems with the new registration system
  src/middlewares/auth.ts
  src/utils/prisma.ts
Labels: fixes

#92 Resolve issues with user creation and new login location system
  src/middlewares/auth.ts
  src/routes/v1/users/auth.ts
Labels: fixes

#93 fix: req.user not found while adding login device
  src/routes/v1/users/auth.ts
Labels: fixes

#100 Disable trackActivity on new accounts by default
  README.md
  prisma/schema.prisma
Labels: fixes
